# Generated by Django 4.1.5 on 2023-01-26 07:42

import asset.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_user', '0002_alter_employee_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('serial_no', models.CharField(blank=True, max_length=40, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('inventory_no', models.CharField(blank=True, max_length=40, null=True)),
                ('identifier', models.CharField(blank=True, help_text='External identifier.', max_length=40, null=True)),
                ('invoice', models.FileField(blank=True, null=True, upload_to='')),
                ('warranty', models.FileField(blank=True, null=True, upload_to='')),
                ('purchased_at', models.DateTimeField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Brand', max_length=50)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetLoanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('contract', models.FileField(blank=True, null=True, upload_to='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_associated_loans', to='asset.asset')),
                ('employee', models.ForeignKey(on_delete=models.SET(asset.models.AssetLoanSession.getSentinelUser), related_name='get_asset_loans_taken', to='custom_user.employee')),
                ('supervisor', models.ForeignKey(on_delete=models.SET(asset.models.AssetLoanSession.getSentinelUser), related_name='get_asset_loans_supervised', to='custom_user.employee')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='brand',
            field=models.ForeignKey(help_text='Brand of the asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_brand_assets', to='asset.brand'),
        ),
        migrations.AddField(
            model_name='asset',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_company_assets', to='custom_user.company'),
        ),
        migrations.AddField(
            model_name='asset',
            name='current_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_associated_assets', to='custom_user.employee'),
        ),
    ]
