# Generated by Django 4.1.5 on 2023-01-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='purchased_at',
            field=models.DateTimeField(null=True),
        ),
    ]
