# Generated by Django 4.1.5 on 2023-01-26 16:19

import asset.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_alter_employee_user'),
        ('asset', '0002_alter_asset_purchased_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetloansession',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=models.SET(asset.models.AssetLoanSession.getSentinelUser), related_name='get_asset_loans_supervised', to='custom_user.employee'),
        ),
    ]
